spring:
  application:
    name: payment-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/payment_gateway
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka